[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
contracts = "3oqHGMC4cKpkMUXbpRUUjAG9RSTSRohpUco3zPBkCEvg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
